---
services:
  mediamtx:
    image: bluenviron/mediamtx:1.13.0
    container_name: mediamtx
    ports:
      - "8554:8554"
    restart: unless-stopped

  ffmpeg-cam1:
    image: jrottenberg/ffmpeg:4.4-alpine
    container_name: ffmpeg-cam1
    depends_on:
      - mediamtx
    volumes:
      - "${VIDEOS_FOLDER}:/videos"
    command: >
      -re -stream_loop -1 -i /videos/cam1.mp4
      -vcodec libx264 -preset veryfast -tune zerolatency
      -acodec aac -ar 44100 -b:a 128k
      -f rtsp rtsp://mediamtx:8554/camera1
  
  ffmpeg-cam2:
    image: jrottenberg/ffmpeg:4.4-alpine
    container_name: ffmpeg-cam2
    depends_on:
      - mediamtx
    volumes:
      - "${VIDEOS_FOLDER}:/videos"
    command: >
      -re -stream_loop -1 -i /videos/cam2.mp4
      -vcodec libx264 -preset veryfast -tune zerolatency
      -acodec aac -ar 44100 -b:a 128k
      -f rtsp rtsp://mediamtx:8554/camera2
